package fi.konstal.example.game2;


/**
 * The type Main.
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 *
 */
public class Main {
    /**
     * The entry point of application.
     *
     * @param args the input arguments
     */
    public static void main(String... args) {
        MenuWindow si = new MenuWindow();
        si.launchThis();
    }
}
