package fi.konstal.engine.util;

import fi.konstal.engine.gameobject.GameActor;
import javafx.event.EventHandler;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import java.util.ArrayList;


/**
 * The type Keyboard input.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public abstract class KeyboardInput implements EventHandler<KeyEvent>{
    private ArrayList<KeyCode> inputs;
    private GameActor go;
    private boolean restrictMovement;
    private boolean showInputs;


    /**
     * Instantiates a new Keyboard input.
     *
     * @param go the go
     */
    public KeyboardInput(GameActor go) {
        this.go = go;
        inputs = new ArrayList<>();
        this.restrictMovement = false;
        this.showInputs = false;
    }

    /**
     * Instantiates a new Keyboard input.
     */
    public KeyboardInput() {
        this.go = null;
        inputs = new ArrayList<>();
        this.restrictMovement = false;
        this.showInputs = false;
    }

    @Override
    public void handle(KeyEvent event) {
        if(event.getEventType() == KeyEvent.KEY_PRESSED) {
            if(!(inputs.contains(event.getCode()))) {
                inputs.add(event.getCode());
            }
        } else if(event.getEventType() == KeyEvent.KEY_RELEASED) {
            inputs.remove(event.getCode());
        }

        if(restrictMovement) {
            restrictedUpdate();
        } else {
            update();
        }

        //print currently pressed keys if true
        if(showInputs) {
            System.out.println(inputs);
        }
    }

    /**
     * Update.
     */
    public abstract void update();

    /**
     * Restricted update.
     */
    public abstract void restrictedUpdate();


    /**
     * Gets game object.
     *
     * @return the game object
     */
    public GameActor getGameObject() {
        return go;
    }

    /**
     * Sets restricted movement.
     *
     * @param b the b
     */
    public void setRestrictedMovement(Boolean b) {
        restrictMovement = b;
    }

    /**
     * Show inputs.
     *
     * @param b the b
     */
    public void showInputs(Boolean b) { showInputs = b; }

    /**
     * Gets inputs.
     *
     * @return the inputs
     */
    public ArrayList<KeyCode> getInputs() {
        return inputs;
    }

    /**
     * Gets go.
     *
     * @return the go
     */
    public GameActor getGo() {
        return go;
    }

    /**
     * Sets go.
     *
     * @param go the go
     */
    public void setGo(GameActor go) {
        this.go = go;
    }
}
