package fi.konstal.engine.util;

import javafx.scene.image.Image;

import java.io.Serializable;

/**
 * The type Sprite animation.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public class SpriteAnimation extends Animation implements Sprite, Serializable {

    /**
     * Instantiates a new Sprite animation.
     *
     * @param filename      the filename
     * @param rows          the rows
     * @param amount        the amount
     * @param width         the width
     * @param height        the height
     * @param xOffset       the x offset
     * @param yOffset       the y offset
     * @param cycleDuration the cycle duration
     */
    public SpriteAnimation(String filename, int rows, int amount, int width, int height, int xOffset, int yOffset, int cycleDuration) {
        super(filename, rows, amount, width, height, xOffset, yOffset, cycleDuration);
    }

    /**
     * Instantiates a new Sprite animation.
     *
     * @param filename      the filename
     * @param rows          the rows
     * @param amount        the amount
     * @param width         the width
     * @param height        the height
     * @param cycleDuration the cycle duration
     */
    public SpriteAnimation(String filename, int rows, int amount, int width, int height, int cycleDuration) {
        super(filename, rows, amount, width, height, 0, 0, cycleDuration);
    }

    /**
     * Instantiates a new Sprite animation.
     */
    public SpriteAnimation() {

    }

    @Override
    public Image getImage() {
        return cycleAnimation();
    }

}
