package fi.konstal.engine.util;


import javafx.scene.image.Image;


/**
 * The type Sprite image.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public class SpriteImage implements Sprite {
    private Image sprite;

    /**
     * Instantiates a new Sprite image.
     *
     * @param filename the filename
     */
    public SpriteImage(String filename) {
        sprite = new Image(filename);
    }


    /**
     * Instantiates a new Sprite image.
     */
    public SpriteImage() {
        sprite = new Image("OvenMitten.jpeg");
    }


    @Override
    public Image getImage() {
        return sprite;
    }


}
