package fi.konstal.engine.util;

import javafx.scene.image.Image;

/**
 * The interface Sprite.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public interface Sprite {
    /**
     * Gets image.
     *
     * @return the image
     */
    Image getImage();
}
