package fi.konstal.example.game1.util;

/**
 * The enum Direction state.
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public enum DirectionState {
    /**
     * Right direction state.
     */
    RIGHT, /**
     * Left direction state.
     */
    LEFT, /**
     * Up direction state.
     */
    UP, /**
     * Down direction state.
     */
    DOWN;
}
