package fi.konstal.engine;

import javafx.application.Application;
import javafx.stage.Stage;

//TODO: use this abstract class for something useful


/**
 * The type Game window.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public abstract class GameWindow extends Application {

    /**
     * Show main menu.
     *
     * @param primaryStage the primary stage
     */
    public abstract void showMainMenu(Stage primaryStage);

    /**
     * Run game.
     *
     * @param primaryStage the primary stage
     */
    public abstract void runGame(Stage primaryStage);

    /**
     * Launch this.
     */
    public abstract void launchThis();

    @Override
    public void start(Stage primaryStage) throws Exception {
        showMainMenu(primaryStage);
    }

    /**
     * Load.
     */
    public void load() {
        //TODO: Implement this
        System.out.println("Loading..");
    }
}
