package fi.konstal.engine.sprite;


import fi.konstal.engine.assetmanager.AssetManager;
import fi.konstal.engine.util.Util;
import javafx.scene.image.Image;


/**
 * The type Sprite image.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public class SpriteImage implements Sprite {
    private int assetKey;

    public SpriteImage(String assetKeyRef, String filename) {
        if (AssetManager.containsRef(assetKeyRef)) {
            this.assetKey = AssetManager.getAssetReference(assetKeyRef);
        } else {
            this.assetKey = Util.getUniqueID();
            AssetManager.addAssetReference(assetKeyRef, assetKey, new Image(filename));
        }
    }

    /**
     * Instantiates a new Sprite image.
     *
     * @param filename the filename
     */
    public SpriteImage( String filename) {
        this.assetKey = Util.getUniqueID();
        AssetManager.addAsset(assetKey, new Image(filename));
    }


    /**
     * Instantiates a new Sprite image.
     */
    public SpriteImage() {
        this.assetKey = Util.getUniqueID();
        AssetManager.addAsset(assetKey, new Image("OvenMitten.jpeg"));
    }


    @Override
    public Image getImage() {
        return AssetManager.getAsset(assetKey, Image.class);
    }


}
