package fi.konstal.engine.sprite;


import fi.konstal.engine.assetmanager.AssetManager;
import javafx.scene.image.Image;


/**
 * The type Sprite image.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public class SpriteImage implements Sprite {
    private Image sprite;
    private String assetKey;

    /**
     * Instantiates a new Sprite image.
     *
     * @param filename the filename
     */
    public SpriteImage(String assetKey, String filename) {
        this.assetKey = assetKey;
        AssetManager.addAsset(assetKey, new Image(filename));
    }


    /**
     * Instantiates a new Sprite image.
     */
    public SpriteImage() {
        sprite = new Image("OvenMitten.jpeg");
    }


    @Override
    public Image getImage() {
        return sprite;
    }


}
