package fi.konstal.example.game1;

/**
 * Created by e4klehti on 22.11.2017.
 *
 * Uhm, I actually ran outta time javadockin, so the rest this autogenerated.
 *
 * @author Konsta Lehtinen
 * @version 2017-12-20
 */
public class Main {
    /**
     * The entry point of application.
     *
     * @param args the input arguments
     */
    public static void main(String... args) {
        MenuWindow sd2000 = new MenuWindow();
        sd2000.launchThis();
    }
}
